version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  settings:
    govet:
      disable:
        - unsafeptr
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        path: internal/x11/shm/
        text: possible misuse of unsafe.Pointer
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
