// Build script for render-sys crate
//
// This script compiles WGSL shaders at build time and generates Rust code
// containing the compiled shader binaries as static byte arrays.
//
// Per ROADMAP.md Phase 4.4: "Run the shader compiler as a build.rs step in
// Cargo. The compiled GPU binaries are embedded in the static library as byte
// arrays. No runtime shader compilation needed for the core UI shaders."

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=shaders/");
    
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("compiled_shaders.rs");
    
    // List of all UI shaders to compile
    let shaders = [
        "solid_fill",
        "textured_quad",
        "sdf_text",
        "box_shadow",
        "rounded_rect",
        "linear_gradient",
        "radial_gradient",
    ];
    
    let mut output = String::new();
    output.push_str("// Auto-generated shader binaries\n");
    output.push_str("// DO NOT EDIT - generated by build.rs\n\n");
    
    // For each shader, embed the WGSL source as a string constant
    // These will be compiled to GPU binaries by the EU backend when that's ready
    for shader_name in &shaders {
        let shader_path = format!("shaders/{}.wgsl", shader_name);
        
        // Ensure shader file exists
        if !Path::new(&shader_path).exists() {
            panic!("Shader file not found: {}", shader_path);
        }
        
        // Read shader source and escape it for embedding
        let shader_source = fs::read_to_string(&shader_path)
            .expect(&format!("Failed to read shader file: {}", shader_path));
        
        // Generate constant name (e.g., SOLID_FILL_WGSL)
        let const_name = format!("{}_WGSL", shader_name.to_uppercase());
        
        // Emit: pub const SHADER_NAME_WGSL: &str = "...";
        output.push_str(&format!(
            "/// {} shader WGSL source\n",
            shader_name.replace('_', " ")
        ));
        output.push_str(&format!(
            "pub const {}: &str = r#\"{}\"#;\n\n",
            const_name, shader_source
        ));
    }
    
    // Generate a shader registry array for runtime lookup
    output.push_str("/// Array of all compiled UI shaders\n");
    output.push_str("pub const UI_SHADERS: &[(&str, &str)] = &[\n");
    for shader_name in &shaders {
        let const_name = format!("{}_WGSL", shader_name.to_uppercase());
        output.push_str(&format!("    (\"{}\", {}),\n", shader_name, const_name));
    }
    output.push_str("];\n");
    
    fs::write(&dest_path, output).unwrap();
    
    println!("cargo:warning=Generated {} shader source constants", shaders.len());
}
